//This file is generated by a script. 
#ifndef _WS2812_PIND_HEADER_H_INCLUDED
#define _WS2812_PIND_HEADER_H_INCLUDED
void neopixel_show_long_P1_0(uint32_t dataAndLen); 
#define neopixel_show_P1_0(ADDR,LEN) neopixel_show_long_P1_0((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_1(uint32_t dataAndLen); 
#define neopixel_show_P1_1(ADDR,LEN) neopixel_show_long_P1_1((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_2(uint32_t dataAndLen); 
#define neopixel_show_P1_2(ADDR,LEN) neopixel_show_long_P1_2((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_3(uint32_t dataAndLen); 
#define neopixel_show_P1_3(ADDR,LEN) neopixel_show_long_P1_3((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_4(uint32_t dataAndLen); 
#define neopixel_show_P1_4(ADDR,LEN) neopixel_show_long_P1_4((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_5(uint32_t dataAndLen); 
#define neopixel_show_P1_5(ADDR,LEN) neopixel_show_long_P1_5((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_6(uint32_t dataAndLen); 
#define neopixel_show_P1_6(ADDR,LEN) neopixel_show_long_P1_6((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P1_7(uint32_t dataAndLen); 
#define neopixel_show_P1_7(ADDR,LEN) neopixel_show_long_P1_7((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_0(uint32_t dataAndLen); 
#define neopixel_show_P3_0(ADDR,LEN) neopixel_show_long_P3_0((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_1(uint32_t dataAndLen); 
#define neopixel_show_P3_1(ADDR,LEN) neopixel_show_long_P3_1((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_2(uint32_t dataAndLen); 
#define neopixel_show_P3_2(ADDR,LEN) neopixel_show_long_P3_2((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_3(uint32_t dataAndLen); 
#define neopixel_show_P3_3(ADDR,LEN) neopixel_show_long_P3_3((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_4(uint32_t dataAndLen); 
#define neopixel_show_P3_4(ADDR,LEN) neopixel_show_long_P3_4((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_5(uint32_t dataAndLen); 
#define neopixel_show_P3_5(ADDR,LEN) neopixel_show_long_P3_5((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_6(uint32_t dataAndLen); 
#define neopixel_show_P3_6(ADDR,LEN) neopixel_show_long_P3_6((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
void neopixel_show_long_P3_7(uint32_t dataAndLen); 
#define neopixel_show_P3_7(ADDR,LEN) neopixel_show_long_P3_7((((uint16_t)(ADDR)) & 0xFFFF) | (((uint32_t)(LEN) & 0xFF) << 16)); 
#endif 
